-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (Registered Users)
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  full_name text,
  avatar_url text,
  phone_number text, 
  social_links jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

-- 2. GUEST IDENTITIES (Anonymous / Shadow Users)
create table guest_identities (
  id uuid primary key, -- Generated by frontend (UUIDv4)
  display_name text not null,
  last_active_at timestamptz default now(),
  created_at timestamptz default now()
);

-- 3. ORGANIZATIONS
create table organizations (
  id uuid default uuid_generate_v4() primary key,
  handle text unique not null,
  name text not null,
  description text,
  logo_url text,
  social_links jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table org_members (
  org_id uuid references organizations(id),
  user_id uuid references profiles(id),
  role text check (role in ('owner', 'admin', 'member')),
  primary key (org_id, user_id)
);

-- 4. EVENTS (The Core)
create table events (
  id uuid default uuid_generate_v4() primary key,
  creator_id uuid references profiles(id),
  org_id uuid references organizations(id),
  
  -- Status flow: draft -> polling -> scheduled -> past
  status text default 'draft' check (status in ('draft', 'polling', 'scheduled', 'cancelled', 'past')),
  
  title text not null,
  description text,
  
  -- Timing (can be null during polling)
  start_time timestamptz,
  end_time timestamptz,
  timezone text default 'UTC',
  
  -- Location
  location_name text,
  location_address text,
  location_url text,
  
  -- Visuals & Config
  cover_image_url text,
  theme_config jsonb default '{}'::jsonb, -- { font, bg_effect, colors }
  modules_config jsonb default '{}'::jsonb, -- { spotify, registry }
  
  -- Constraints
  max_capacity int,
  show_guest_list boolean default true,
  
  created_at timestamptz default now()
);

-- 5. DATE POLLING (Find a time)
create table event_time_polls (
  id uuid default uuid_generate_v4() primary key,
  event_id uuid references events(id) not null,
  start_time timestamptz not null,
  end_time timestamptz
);

create table event_poll_votes (
  id uuid default uuid_generate_v4() primary key,
  poll_id uuid references event_time_polls(id) not null,
  
  -- Hybrid Identity: Must have either user_id OR guest_id
  user_id uuid references profiles(id),
  guest_id uuid references guest_identities(id),
  
  status text check (status in ('yes', 'if_need_be', 'no')),
  created_at timestamptz default now(),
  
  constraint check_identity check (user_id is not null or guest_id is not null)
);

-- 6. RSVPS & GUEST LIST
create table rsvps (
  id uuid default uuid_generate_v4() primary key,
  event_id uuid references events(id) not null,
  
  user_id uuid references profiles(id),
  guest_id uuid references guest_identities(id),
  
  status text not null check (status in ('going', 'maybe', 'not_going', 'waitlist')),
  guests_count int default 0, -- Plus ones
  comment text,
  phone_number text,
  
  created_at timestamptz default now(),
  
  constraint check_identity_rsvp check (user_id is not null or guest_id is not null),
  -- Prevent duplicate RSVP for same person
  constraint unique_user_rsvp unique nulls not distinct (event_id, user_id),
  constraint unique_guest_rsvp unique nulls not distinct (event_id, guest_id)
);

-- 7. ACTIVITY FEED
create table activities (
  id uuid default uuid_generate_v4() primary key,
  event_id uuid references events(id) not null,
  user_id uuid references profiles(id),
  guest_id uuid references guest_identities(id),
  
  type text check (type in ('blast', 'comment', 'photo', 'rsvp_log')),
  content text,
  media_url text,
  created_at timestamptz default now()
);

-- Enable RLS (Row Level Security) - Basic Setup
alter table profiles enable row level security;
alter table events enable row level security;
alter table rsvps enable row level security;
alter table guest_identities enable row level security;
alter table event_poll_votes enable row level security;
alter table activities enable row level security;

-- Policies (Simplified for dev start)
create policy "Public events are viewable by everyone" on events for select using (true);
create policy "Anyone can insert guest identity" on guest_identities for insert with check (true);
create policy "Anyone can read guest identities" on guest_identities for select using (true);
create policy "Anyone can update their own guest identity" on guest_identities for update using (true);

-- RSVP policies
create policy "Anyone can view RSVPs" on rsvps for select using (true);
create policy "Anyone can create RSVP" on rsvps for insert with check (true);
create policy "Users can update their own RSVP" on rsvps for update using (
  (user_id = auth.uid()) or (guest_id::text = current_setting('app.current_guest_id', true))
);

-- Poll vote policies
create policy "Anyone can view poll votes" on event_poll_votes for select using (true);
create policy "Anyone can vote in polls" on event_poll_votes for insert with check (true);
create policy "Users can update their own votes" on event_poll_votes for update using (
  (user_id = auth.uid()) or (guest_id::text = current_setting('app.current_guest_id', true))
);

-- Activity policies
create policy "Anyone can view activities" on activities for select using (true);
create policy "Anyone can create activities" on activities for insert with check (true);

